server:
  port: 0

spring:
  application:
    name: movie-info-service

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true

movie_db:
  api_key: 7f46651666f1ca68e4cf0cb150551f07
  url:
    discover:
      movie: https://api.themoviedb.org/3/movie/%s?api_key=${movie_db.api_key}
      movies: https://api.themoviedb.org/3/discover/movie?api_key=${movie_db.api_key}
