server:
  port: 0

spring:
  cloud:
    config:
      discovery:
        enabled: true
  application:
    name: movie-rating-service

eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://localhost:8761/service-discovery/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true