server:
  port: 0

spring:
  application:
    name: movie-catalog-service

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true

info-service:
  name: movie-info-service
  movie-info: "http://172.17.19.44:43153/movies/"

rating-service:
  name: movie-rating-service
  user-rating: "http://172.17.19.44:42433/ratings/user/"