server:
  port: 0

spring:
  cloud:
    config:
      discovery:
        enabled: true
  application:
    name: movie-catalog-service

eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://localhost:8761/service-discovery/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

info-service:
  name: MOVIE-INFO-SERVICE
  movie-info: http://${info-service.name}/movies/

rating-service:
  name: movie-rating-service
  user-rating: http://${rating-service.name}/ratings/user/